### ISSUE TITLE
beanstalkdListenAddress paramtere doesn't work on ubuntu

### ISSUE THREAD

**Issue by borzoj** [jasonj/ansible-beanstalkd#4]
/etc/default/beanstalkd looks like this on ubuntu:

```
BEANSTALKD_LISTEN_ADDR=0.0.0.0
BEANSTALKD_LISTEN_PORT=11300

# You can use BEANSTALKD_EXTRA to pass additional options. See beanstalkd(1)
# for a list of the available options. Uncomment the following line for
# persistent job storage.
#BEANSTALKD_EXTRA="-b /var/lib/beanstalkd"

DAEMON_OPTS="-l 0.0.0.0 -p 11300 -b /var/lib/beanstalkd"

```

the "edit /etc/default/beanstalkd DAEMON_OPTS, set listener info and persistent storage options"
task only changes DAEMON_OPTS but service uses the 
BEANSTALKD_LISTEN_ADDR

**Comment by jasonj** [comment]
I really need to turn on notifications :) Thanks, and merged.
